name: ac-advisor
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - catboost
  - xgboost
  - matplotlib
  - plotly
  - shap
  - streamlit
  - jupyterlab
  - pip:
      - mlflow
      - joblib
      - pydantic>=2
      - ruff
      - black